spring:
  cloud:
    function:
      definition: salesOrderPlacedSupplier;salesOrderAssessedConsumer;salesOrderProcessedConsumer
    stream:
      bindings:
        salesOrderPlacedSupplier-out-0:
          destination: sales.order.placed
        salesOrderAssessedConsumer-in-0:
          destination: sales.order.assessed
        salesOrderProcessedConsumer-in-0:
          destination: sales.order.processed

