openapi: 3.0.1
info:
  title: FineTech Catalog API
  version: '1.0.0'
  description: |
    The Catalog API allows you recieve products from FineTech's product catalog.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: API support
    email: api@finetech.dk
      
externalDocs:
  description: Customer API
  url: https://developer.finetech.dk/sales
servers:
  - description: local
    url: http://localhost:8080
  - description: test
    url: https://test-api.finetech.dk
tags:
  - name: Sales    
paths:
  /catalogs:
    get:
      tags:
        - Sales
      description: Get product catalogs
      operationId: getProductCatalogs
      security: 
        - oauth2:
          - 'read:catalog'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogPage'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized
          content:
            application/problem+json: {}
        '403':
          description: Forbidden
          content:
            application/problem+json: {}
        '500':
          description: Internal Server Error
          content:
            application/problem+json: {}
  /catalogs/{name}:
    get:
      tags:
        - Sales
      description: Get product catalog by name
      operationId: getProductCatalog
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      security: 
        - oauth2:
          - 'read:catalog'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogPage'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized
          content:
            application/problem+json: 
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: Forbidden
          content:
            application/problem+json: 
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json: 
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    CatalogPage:
      type: object
      properties:
        items: 
          type: array
          items:
            $ref: '#/components/schemas/Catalog'
    Catalog:
      type: object
      properties:
        name: 
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Product:
      type: object
      properties:
        catalog_name:
          type: string
        number:
          type: string
        display_name:
          type: string
        quote_criteria:
          type: array
          items:
            $ref: '#/components/schemas/Criterion'
    Criterion:
      type: object
      properties:
        name:
          type: string
        display_name:
          type: string
        value:
          type: string
        type:
          type: string
          enum:
            - boolean
            - integer
            - decimal
            - date
            - string
        allow_values:
          type: array
          items:
            type: object
            properties:
              key:
                type: string
              display_value:
                type: string
              selected:
                type: boolean
        allow_mulitiselect:
          type: boolean
        allow_limit:
          type: object
          properties:
            min_value:
              type: string
            min_inclusive:
              type: boolean
            max_value:
              type: string
            max_inclusive:
              type: string
            
    Problem:
      type: object
      properties:
        type:
          type: string
          description: URI that identifies the problem type.
        title:
          type: string
          description: A short, summary of the problem type.
        status:
          type: integer
          description: The HTTP status code 
        detail:
          type: string
          description: An explanation specific to the problem.
        instance:
          type: string
          description: An URI that identifies the occurrence of the problem.
  securitySchemes:
    openid-connect:
        type: openIdConnect
        openIdConnectUrl: https://finetech-test.eu.auth0.com/.well-known/openid-configuration
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://finetech-test.eu.auth0.com/oauth/token
          scopes: 
            'read:catalog': Allows to read catalog 
security: 
  - oauth2:
    - 'read:catalog'