spring:
  cloud:
    function:
      definition: handleSalesProductCatalog;handleSalesProductInformation;handleSalesProductPrice
    stream:
      bindings:
        handleSalesProductCatalog-in-0:
          destination: sales.product.catalog
        handleSalesProductInformation-in-0:
          destination: sales.product.information
        handleSalesProductPrice-in-0:
          destination: sales.product.price

