spring:
  cloud:
    function:
      definition: handleSalesProductCatalog;handleSalesProductInformation;handleSalesProductPrice
    stream:
      bindings:
        handleSalesProductCatalog-out-0:
          destination: sales.product.catalog
        handleSalesProductInformation-out-0:
          destination: sales.product.information
        handleSalesProductPrice-out-0:
          destination: sales.product.price
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'

