spring:
  cloud:
    function:
      definition: salesProductCatalogConsumer;salesProductInformationConsumer;salesProductPriceConsumer
    stream:
      bindings:
        salesProductCatalogConsumer-in-0:
          destination: sales.product.catalog
        salesProductInformationConsumer-in-0:
          destination: sales.product.information
        salesProductPriceConsumer-in-0:
          destination: sales.product.price

