spring:
  cloud:
    function:
      definition: publishSalesProductCatalog;publishSalesProductInformation;publishSalesProductPrice
    stream:
      bindings:
        publishSalesProductCatalog-in-0:
          destination: sales.product.catalog
        publishSalesProductInformation-in-0:
          destination: sales.product.information
        publishSalesProductPrice-in-0:
          destination: sales.product.price

