spring:
  cloud:
    function:
      definition: salesProductCatalogSupplier;salesProductInformationSupplier;salesProductPriceSupplier
    stream:
      bindings:
        salesProductCatalogSupplier-out-0:
          destination: sales.product.catalog
        salesProductInformationSupplier-out-0:
          destination: sales.product.information
        salesProductPriceSupplier-out-0:
          destination: sales.product.price

