spring:
  cloud:
    function:
      definition: publishSalesProductCatalog;publishSalesProductInformation;publishSalesProductPrice
    stream:
      bindings:
        publishSalesProductCatalog-out-0:
          destination: sales.product.catalog
        publishSalesProductInformation-out-0:
          destination: sales.product.information
        publishSalesProductPrice-out-0:
          destination: sales.product.price

