asyncapi: '2.4.0'
id: 'finetech:sales:product'
info:
  title: Finetech Sales Product AsyncAPI
  version: '1.0.0'
  description: |
    The Product AsyncAPI publishes events when ever changes occurs to catalogs, products or prices.
  contact:
    email: api@finetech.dk
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  staging-broker:
    url: pkc-1wvvj.westeurope.azure.confluent.cloud:9092
    protocol: kafka
    protocolVersion: 2.6.0
    description: Finetech Test Broker

channels:
  sales.product.catalog:
    publish:
      message:
        $ref: '#/components/messages/CatalogEvent'
  sales.product.information:
    publish:
      message:
        $ref: '#/components/messages/ProductInformationEvent'
  sales.product.price:
    publish:
      message:
        $ref: '#/components/messages/PriceEvent'

components:
  messages:
    CatalogEvent:
      payload:
        $ref: 'https://raw.githubusercontent.com/finetech-dk/specs/main/sales/product/json-schema/product-catalog.json'
      description: >-
        The CatalogEvent is based on CloudEvent spec and contains the changed Catalog information.
      schemaFormat: application/vnd.aai.asyncapi+json;version=2.0.0
      contentType: application/json
    ProductInformationEvent:
      payload:
        $ref: 'https://raw.githubusercontent.com/finetech-dk/specs/main/sales/product/json-schema/product-catalog.json'
      description: >-
        The ProductInformation is based on CloudEvent spec and contains the changed Product information.
      schemaFormat: application/vnd.aai.asyncapi+json;version=2.0.0
      contentType: application/json
    PriceEvent:
      payload:
        $ref: 'https://raw.githubusercontent.com/finetech-dk/specs/main/sales/product/json-schema/product-catalog.json'
      description: >-
        The PriceEvent is based on CloudEvent spec and contains the changed Price information.
      schemaFormat: application/vnd.aai.asyncapi+json;version=2.0.0
      contentType: application/json
    